/**
  ******************************************************************************
  * @file        AppProtectEvent.h
  * @author      Johnny
  * @version     v0.0
  * @date        2021/9/7
  * @brief       
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; COPYRIGHT(c) 2021 Johnny</center></h2>
  *
  *
  ******************************************************************************
  */
  
#ifndef _APP_PROTECT_EVENT_H_
#define _APP_PROTECT_EVENT_H_

enum{
	APP_PROTECT_OVP_L1_SET=1,
	APP_PROTECT_OVP_L2_SET,
	APP_PROTECT_OVP_L3_SET,
	APP_PROTECT_OVP_L1_RELEASE,
	APP_PROTECT_OVP_L2_RELEASE,
	APP_PROTECT_OVP_L3_RELEASE,

	APP_PROTECT_UVP_L1_SET,
	APP_PROTECT_UVP_L2_SET,
	APP_PROTECT_UVP_L3_SET,
	APP_PROTECT_UVP_L1_RELEASE,
	APP_PROTECT_UVP_L2_RELEASE,
	APP_PROTECT_UVP_L3_RELEASE,
	
	APP_PROTECT_COTP_L1_SET,
	APP_PROTECT_COTP_L2_SET,
	APP_PROTECT_COTP_L3_SET,
	APP_PROTECT_COTP_L4_SET,
	APP_PROTECT_COTP_L1_RELEASE,
	APP_PROTECT_COTP_L2_RELEASE,
	APP_PROTECT_COTP_L3_RELEASE,
	APP_PROTECT_COTP_L4_RELEASE,		

	APP_PROTECT_CUTP_L1_SET,
	APP_PROTECT_CUTP_L2_SET,
	APP_PROTECT_CUTP_L3_SET,
	APP_PROTECT_CUTP_L4_SET,
	APP_PROTECT_CUTP_L1_RELEASE,		
	APP_PROTECT_CUTP_L2_RELEASE,
	APP_PROTECT_CUTP_L3_RELEASE,
	APP_PROTECT_CUTP_L4_RELEASE,
	
	APP_PROTECT_DOTP_L1_SET,
	APP_PROTECT_DOTP_L2_SET,		
	APP_PROTECT_DOTP_L3_SET,
	APP_PROTECT_DOTP_L1_RELEASE,
	APP_PROTECT_DOTP_L2_RELEASE,
	APP_PROTECT_DOTP_L3_RELEASE,

	APP_PROTECT_DUTP_L1_SET,
	APP_PROTECT_DUTP_L2_SET,		
	APP_PROTECT_DUTP_L3_SET,
	APP_PROTECT_DUTP_L1_RELEASE,
	APP_PROTECT_DUTP_L2_RELEASE,
	APP_PROTECT_DUTP_L3_RELEASE,

	APP_PROTECT_DOCP_L1_SET,		
	APP_PROTECT_DOCP_L2_SET,
	APP_PROTECT_DOCP_L3_SET,
	APP_PROTECT_DOCP_L4_SET,
	APP_PROTECT_DOCP_L1_RELEASE,
	APP_PROTECT_DOCP_L2_RELEASE,
	APP_PROTECT_DOCP_L3_RELEASE,
	APP_PROTECT_DOCP_L4_RELEASE,
	
	APP_PROTECT_COCP_L1_SET,
	APP_PROTECT_COCP_L2_SET,	
	APP_PROTECT_COCP_L3_SET,
	APP_PROTECT_COCP_L4_SET,
	APP_PROTECT_COCP_L1_RELEASE,
	APP_PROTECT_COCP_L2_RELEASE,
	APP_PROTECT_COCP_L3_RELEASE,
	APP_PROTECT_COCP_L4_RELEASE,

	APP_PROTECT_OVP_PF,
	APP_PROTECT_UVP_PF,
	
	APP_PROTECT_EVENT
};


#endif /* _APP_PROTECT_EVENT_H_ */


/************************ (C) COPYRIGHT Johnny Wang *****END OF FILE****/    
